name: Publish Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-installers:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew preparePackagedReleaseDistributionForCurrentOS

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: installers
          if-no-files-found: error
          path: installers

  build-win-portable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew preparePortableReleaseDistribution

      - name: Zip Portable
        uses: montudor/action-zip@v1
        with:
        args: zip -qq -r portables/StuffIRead-Win-Portable.zip portable

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: portables
          if-no-files-found: error
          path: portables/StuffIRead-Win-Portable.zip

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Installers
        uses: actions/download-artifact@v3
        with:
          name: installers

      - name: Get Portables
        uses: actions/download-artifact@v3
        with:
          name: portables

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: endsWith(github.ref_name, 'DRAFT')
          prerelease: endsWith(github.ref_name, 'PRERELEASE')
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            installers/**
            portables/**
            LICENSE.txt