name: Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: endsWith(github.ref_name, 'DRAFT')
          prerelease: endsWith(github.ref_name, 'PRERELEASE')
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            build/compose/binaries/main-release/dmg/**
            build/compose/binaries/main-release/msi/**
            build/compose/binaries/main-release/deb/**
            LICENSE.txt