# Create release for tag pushed into master branch
name: Release

on:
  push:
    branches:
      - master
    tags:
      - *

jobs:
  build:
    uses: ./.github/workflows/build-job.yml
  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: get-binaries
        name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-binaries
          path: binaries

      - name: List binaries in release
        run: ls -R binaries/ || true

      - name: Checkout license file
        uses: Bhacaz/checkout-files@v2
        with:
          files: LICENSE.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: endsWith(github.ref_name, 'DRAFT')
          prerelease: endsWith(github.ref_name, 'PRERELEASE')
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            binaries/**
            LICENSE.txt